// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionService.Data;

#nullable disable

namespace TransactionService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304125609_AddFraudModelFeatureColumns")]
    partial class AddFraudModelFeatureColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionService.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccountAgeDays")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerAge")
                        .HasColumnType("int");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DistanceFromHomeKm")
                        .HasColumnType("float");

                    b.Property<string>("FraudModelVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FraudPrediction")
                        .HasColumnType("bit");

                    b.Property<float?>("FraudProbability")
                        .HasColumnType("real");

                    b.Property<string>("FraudReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FraudScore")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FraudScoredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("IsInternational")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNewDevice")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNewPaymentToken")
                        .HasColumnType("bit");

                    b.Property<double?>("MccRisk")
                        .HasColumnType("float");

                    b.Property<string>("MerchantCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentMethodAgeDays")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethodToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("TotalAmountLast24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TxnCountLast1h")
                        .HasColumnType("int");

                    b.Property<int?>("TxnCountLast24h")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
