using TransactionService.Models;

namespace TransactionService.Simulation
{
    /// <summary>
    /// A transaction generated by the simulator, tagged with the ground-truth
    /// label the simulator intended (fraud scenario or normal traffic) so a run
    /// can be scored for real accuracy, not just prediction volume.
    /// </summary>
    public sealed record SimulatedTransaction(
        CreateTransactionRequest Request,
        bool ExpectedFraud,
        string Scenario);
}