namespace TransactionService.Models
{
    /// <summary>
    /// Represents a single payment transaction in the system.
    ///
    /// This entity is used by the Transaction API and persisted to the database.
    /// It contains:
    /// - core transaction fields (amount, currency, parties, timestamp),
    /// - contextual fields used for feature engineering (device/channel/geo),
    /// - optional engineered features (velocity, risk signals),
    /// - optional fraud scoring outputs produced asynchronously by the worker.
    /// </summary>
    public sealed class Transaction
    {
        /// <summary>
        /// Unique identifier for the transaction.
        /// Generated by the API when the transaction is created.
        /// </summary>
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Transaction amount in the specified <see cref="Currency"/>.
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// ISO 4217 currency code (e.g., "AUD", "USD").
        /// </summary>
        public string Currency { get; set; } = "AUD";

        /// <summary>
        /// Identifier of the merchant processing the transaction.
        /// </summary>
        public string MerchantId { get; set; } = string.Empty;

        /// <summary>
        /// Identifier of the customer initiating the transaction.
        /// </summary>
        public string CustomerId { get; set; } = string.Empty;

        /// <summary>
        /// Tokenized representation of the payment method.
        /// Raw card/bank details are never stored.
        /// </summary>
        public string PaymentMethodToken { get; set; } = string.Empty;

        /// <summary>
        /// Identifier of the device used to initiate the transaction.
        /// </summary>
        public string DeviceId { get; set; } = string.Empty;

        /// <summary>
        /// ISO 3166-1 alpha-2 country code where the transaction took place (e.g., "AU", "US").
        /// </summary>
        public string Country { get; set; } = "AU";

        /// <summary>
        /// Time the transaction occurred. Defaults to UTC if not explicitly set.
        /// </summary>
        public DateTimeOffset Timestamp { get; set; } = DateTimeOffset.UtcNow;

        // ---------------------------------------------------------------------
        // Context fields (typically supplied by the API/client and used as model inputs)
        // ---------------------------------------------------------------------

        /// <summary>
        /// High-level payment rail / type (e.g., "CARD_DEBIT", "BANK_TRANSFER").
        /// </summary>
        public string? TransactionType { get; set; }

        /// <summary>
        /// Channel through which the transaction occurred (e.g., "ECOM", "IN_STORE").
        /// </summary>
        public string? Channel { get; set; }

        /// <summary>
        /// Merchant category bucket (MCC-style grouping used by the system).
        /// </summary>
        public string? MerchantCategory { get; set; }

        /// <summary>
        /// Device category (e.g., "MOBILE", "DESKTOP", "ATM").
        /// </summary>
        public string? DeviceType { get; set; }

        /// <summary>
        /// Customer's home country (ISO 3166-1 alpha-2), used to determine international activity.
        /// </summary>
        public string? CustomerHomeCountry { get; set; }

        /// <summary>
        /// Optional risk tier assigned to the merchant (e.g., "LOW", "MED", "HIGH").
        /// </summary>
        public string? MerchantRiskTier { get; set; }

        /// <summary>
        /// Optional latitude where the transaction occurred.
        /// </summary>
        public double? Latitude { get; set; }

        /// <summary>
        /// Optional longitude where the transaction occurred.
        /// </summary>
        public double? Longitude { get; set; }

        /// <summary>
        /// Optional distance from the customer's expected/home location in kilometers.
        /// This can be supplied by the API or computed from geo signals elsewhere.
        /// </summary>
        public double? DistanceFromHomeKm { get; set; }

        // ---------------------------------------------------------------------
        // Engineered/derived features (computed by FraudDetectionWorker)
        // ---------------------------------------------------------------------

        /// <summary>
        /// Indicates whether the device is new for this customer.
        /// </summary>
        public bool? IsNewDevice { get; set; }

        /// <summary>
        /// Indicates whether the payment token is new for this customer.
        /// </summary>
        public bool? IsNewPaymentToken { get; set; }

        /// <summary>
        /// Indicates whether the transaction country differs from the customer's home country.
        /// </summary>
        public bool? IsInternational { get; set; }

        /// <summary>
        /// Customer account age in days at the time of transaction.
        /// </summary>
        public int? AccountAgeDays { get; set; }

        /// <summary>
        /// Customer age in years (if available in customer state/profile).
        /// </summary>
        public int? CustomerAge { get; set; }

        /// <summary>
        /// Number of transactions by the customer in the last hour.
        /// </summary>
        public int? TxnCountLast1h { get; set; }

        /// <summary>
        /// Number of transactions by the customer in the last 24 hours.
        /// </summary>
        public int? TxnCountLast24h { get; set; }

        /// <summary>
        /// Total spend by the customer in the last 24 hours.
        /// </summary>
        public decimal? TotalAmountLast24h { get; set; }

        /// <summary>
        /// Age of the payment method token for this customer in days.
        /// </summary>
        public int? PaymentMethodAgeDays { get; set; }

        /// <summary>
        /// Merchant category risk score (typically 0..1 range), derived from the MCC risk table.
        /// </summary>
        public double? MccRisk { get; set; }

        // ---------------------------------------------------------------------
        // Fraud scoring outputs (written by FraudDetectionWorker)
        // ---------------------------------------------------------------------

        /// <summary>
        /// Fraud score used for ranking/alerting (higher implies higher risk).
        /// </summary>
        public int? FraudScore { get; set; }

        /// <summary>
        /// Human-readable reason codes describing why the transaction is risky.
        /// This is intended for demo/explainability and operational visibility.
        /// </summary>
        public string? FraudReason { get; set; }

        /// <summary>
        /// Timestamp when the worker produced the fraud assessment.
        /// </summary>
        public DateTimeOffset? FraudScoredAt { get; set; }

        /// <summary>
        /// Model probability of fraud (0.0 to 1.0).
        /// </summary>
        public float? FraudProbability { get; set; }

        /// <summary>
        /// Model predicted label: true = fraud, false = not fraud.
        /// </summary>
        public bool? FraudPrediction { get; set; }

        /// <summary>
        /// Version identifier for the model used to score this transaction.
        /// Useful for auditing and debugging model changes over time.
        /// </summary>
        public string? FraudModelVersion { get; set; }
    }
}