// <auto-generated />
using System;
using FraudDetectionWorker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FraudDetectionWorker.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    partial class TransactionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FraudDetectionWorker.Data.CustomerDeviceState", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CustomerId", "DeviceId");

                    b.ToTable("CustomerDeviceState", (string)null);
                });

            modelBuilder.Entity("FraudDetectionWorker.Data.CustomerPaymentTokenState", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentMethodToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CustomerId", "PaymentMethodToken");

                    b.ToTable("CustomerPaymentTokenState", (string)null);
                });

            modelBuilder.Entity("FraudDetectionWorker.Data.CustomerProfileState", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("AccountCreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CustomerAgeYears")
                        .HasColumnType("int");

                    b.Property<string>("HomeCountry")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomerProfileState", (string)null);
                });

            modelBuilder.Entity("FraudDetectionWorker.Data.MerchantCategoryRisk", b =>
                {
                    b.Property<string>("MerchantCategory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Risk")
                        .HasColumnType("float");

                    b.HasKey("MerchantCategory");

                    b.ToTable("MerchantCategoryRisk", (string)null);
                });

            modelBuilder.Entity("FraudDetectionWorker.Data.TransactionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccountAgeDays")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerAge")
                        .HasColumnType("int");

                    b.Property<string>("CustomerHomeCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DistanceFromHomeKm")
                        .HasColumnType("float");

                    b.Property<string>("FraudModelVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FraudPrediction")
                        .HasColumnType("bit");

                    b.Property<float?>("FraudProbability")
                        .HasColumnType("real");

                    b.Property<string>("FraudReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FraudScore")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FraudScoredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("IsInternational")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNewDevice")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNewPaymentToken")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<double?>("MccRisk")
                        .HasColumnType("float");

                    b.Property<string>("MerchantCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MerchantRiskTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentMethodAgeDays")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethodToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("TotalAmountLast24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TxnCountLast1h")
                        .HasColumnType("int");

                    b.Property<int?>("TxnCountLast24h")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Timestamp");

                    b.HasIndex("MerchantId", "Timestamp");

                    b.ToTable("Transactions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
